#!/usr/bin/env python3
"""Render one section's pass timings as a PNG table.
python sectionTimes.py 138-times.csv --section 3 -o 138-section3-times.png
"""
import argparse
import csv
import math
from pathlib import Path
import sys
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def render(file, section, output, title=None):
    with file.open(newline='', encoding='utf-8-sig') as stream:
        reader = csv.DictReader(stream)
        required = {'Section', 'Pass', 'EntryTime', 'ExitTime', 'SectionTime', 'BehindBest', 'Complete'}
        if not required.issubset(reader.fieldnames or []):
            raise ValueError('Input must be the timing CSV generated by track.py --summary.')
        rows = [row for row in reader if int(row['Section']) == section]
    if not rows:
        raise ValueError(f'No passes found for section {section}.')
    def complete(row):
        return row['Complete'].strip().lower() == 'true'
    def numeric(row, field):
        value = float(row[field])
        if not math.isfinite(value):
            raise ValueError(f'{field} must be finite.')
        return value
    rows.sort(key=lambda row: (not complete(row),
                              numeric(row, 'BehindBest') if complete(row) else 0,
                              int(row['Pass'])))
    def seconds(value):
        return f'{float(value):.3f}' if value.strip() else '—'
    table_rows = [[row['Pass'], seconds(row['EntryTime']), seconds(row['ExitTime']),
                   seconds(row['SectionTime']) if complete(row) else '—',
                   seconds(row['BehindBest']) if complete(row) else '—',
                   'Complete' if complete(row) else 'Partial'] for row in rows]
    fig, ax = plt.subplots(figsize=(10, max(3, 1.7 + .36 * len(rows))))
    ax.axis('off')
    ax.set_title(title or f'{file.stem.removesuffix("-times")} — Section {section} times',
                 fontsize=17, pad=20)
    table = ax.table(cellText=table_rows,
                     colLabels=['Pass', 'Entry (s)', 'Exit (s)', 'Time (s)', 'Behind best (s)', 'Status'],
                     cellLoc='center', loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1, 1.65)
    for (r, c), cell in table.get_celld().items():
        cell.set_edgecolor('#d2d8df')
        if r == 0:
            cell.set_facecolor('#243b53')
            cell.set_text_props(color='white', weight='bold')
        else:
            cell.set_facecolor('#f0f4f8' if r % 2 == 0 else 'white')
            if r == 1 and complete(rows[0]):
                cell.set_facecolor('#dcefdc')
            elif not complete(rows[r-1]):
                cell.set_text_props(color='#687782')
    fig.text(.5, .04, 'Fastest first • Partial visits listed last • Display rounded to 0.001 s',
             ha='center', fontsize=9, color='#52606d')
    fig.tight_layout(rect=(0, .09, 1, 1))
    fig.savefig(output, dpi=180, bbox_inches='tight')
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('file', type=Path, help='track.py timing summary CSV')
    parser.add_argument('--section', required=True, type=int)
    parser.add_argument('-o', '--output', type=Path)
    parser.add_argument('--title')
    args = parser.parse_args()
    if args.section < 1:
        parser.error('--section must be positive.')
    output = args.output or args.file.with_name(
        f'{args.file.stem.removesuffix("-times")}-section{args.section}-times.png')
    if output.resolve() == args.file.resolve():
        parser.error('Output must differ from input.')
    render(args.file, args.section, output, args.title)
    print(output)


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError, csv.Error) as exc:
        print(f'sectionTimes.py: error: {exc}', file=sys.stderr)
        sys.exit(2)
